[theme]
base = "dark"
primaryColor = "#C9924A"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#141414"
textColor = "#e4ddd3"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "warning"
